			-- TABELA HEROI --
DROP TABLE IF EXISTS HEROI;

CREATE TABLE HEROI
(
NOME_HEROI              VARCHAR(40)         NOT NULL,
NOME_REAL               VARCHAR(60)         PRIMARY KEY,
SEXO                    VARCHAR(1)			NOT NULL, -- M: MASCULINO, F: FEMININO, O: OUTRO
ALTURA                  INT          		NOT NULL, -- EM CENTÍMETROS
PESO                    DECIMAL(5,2)        NOT NULL, -- EM KG COM DUAS CASAS DECIMAIS
DATA_NASCIMENTO         DATE                NOT NULL,
LOCAL_NASCIMENTO        VARCHAR(40)         NOT NULL,
PODERES                 TEXT                NOT NULL,
NIVEL_FORCA             INT          	 	NOT NULL, -- ENTRE 0 E 100
POPULARIDADE            INT           		NOT NULL, -- ENTRE 0 E 100
STATUS                  VARCHAR(1)          NOT NULL, -- A: ATIVO, I: INATIVO, B: BANIDO
HISTORICO_BATALHAS      TEXT                NOT NULL
);

            -- TABELA CRIME --
DROP TABLE IF EXISTS CRIME;

CREATE TABLE CRIME
(
ID_CRIME            INT          	PRIMARY KEY AUTO_INCREMENT,
NOME_CRIME          VARCHAR(20)     NOT NULL,
DESCRICAO_CRIME     VARCHAR(200)    NOT NULL,
DATA                DATE            NOT NULL,
HEROI_RESPONSAVEL   VARCHAR(40)     NOT NULL,
SEVERIDADE          INT          	NOT NULL -- ENTRE 1 E 10
);

        -- TABELA MISSÕES --
DROP TABLE IF EXISTS MISSOES;

CREATE TABLE MISSOES
(
ID_MISSAO           INT          	PRIMARY KEY AUTO_INCREMENT,
NOME_MISSAO         VARCHAR(20)     NOT NULL,
DESCRICAO_MISSAO    VARCHAR(200)    NOT NULL,
DIFICULDADE         INT          	NOT NULL, -- ENTRE 1 E 10
HEROIS              TEXT            NOT NULL,
RESULTADO           VARCHAR(1)      NOT NULL -- S: SUCESSO, F: FRACASSO
-- RECOMPENSA                        NOT NULL,
);